- Makefile
- browser/bundle.js
- browser/toBundle.js
- docs-swagger/server.js
- owncloud/appManagement.js
- owncloud/groupManagement.js
- owncloud/helperFunctions.js
- owncloud/owncloud.js
- owncloud/shareManagement.js
- owncloud/userManagement.js
- package.json
- webpack.config.js
Fixes #20 
Introduced a make end point which will automatically make a browser compatible JS dist under the browser folder by the name, ```bundle.js```.
> Browser compatibility

- owncloud/fileManagement.js
- owncloud/helperFunctions.js
- owncloud/shareManagement.js
- owncloud/test/test.js
- owncloud/test/testUnauthenticated.js
- owncloud/test/testUnauthorized.js
- package.json
Fixes #29 
Added unauthorized and unauthenticated tests.
@PVince81
> Un-Authorized and Un-Authenticated unit tests added

- docs-swagger/api/swagger/swagger.yaml
- owncloud/fileInfo.js
> Not removing the namespace from DAV response

- docs-swagger/server.js
- swagger.config.js
Fixes #27 
I haven't removed `initLibrary` and `login` functions from the swagger-ui in case anyone wants to change the owncloudURL or the logged in user.
Question1: What if the configs provided in the swagger.config.js file are invalid?
Question2: Add swagger.config.js to gitignore?
@PVince81
> Made a new swagger config file for instance, username and password

- browser/bundle.js
- owncloud/appManagement.js
- owncloud/fileInfo.js
- owncloud/groupManagement.js
- owncloud/helperFunctions.js
- owncloud/owncloud.js
- owncloud/shareManagement.js
- owncloud/test/testXmlParser.js
- owncloud/userManagement.js
- owncloud/xmlParser/index.js
- package.json
> Changed all occurrences of namepsace

- README.md
Added a GIF showing how Swagger can be used for Issue #14
> Adding Swagger GIF to README.md

- README.md
> Added browser example project in readme

- .gitignore
- .travis.yml
- README.md
- owncloud/appManagement.js
> Fix travis

- owncloud/fileManagement.js
- owncloud/helperFunctions.js
- package.json
- yarn.lock
> Use davclient.js for DAV requests to owncloud

- owncloud/fileInfo.js
- owncloud/fileManagement.js
- owncloud/fileVersionManagement.js
- owncloud/helperFunctions.js
- owncloud/owncloud.js
- tests/fileVersionTest.js
Fixes https://github.com/owncloud/js-owncloud-client/issues/93
So far blocked because of missing prerequisites like https://github.com/owncloud/js-owncloud-client/issues/25 which we might want to first do in a separate PR.
Tests currently fail.
> Add functions for version management

- src/fileManagement.js
- src/fileVersionManagement.js
- tests/fileVersionTest.js
> FilesVersions: restore and get contents of versions has been added

- src/fileManagement.js
- tests/filesTest.js
a list of properties can now be passed into the search method - just like with list
> Add properties to search method

- package.json
- yarn.lock
refs https://github.com/owncloud/owncloud-sdk/issues/184
> Setup babel and browserslist

- src/helperFunctions.js
- src/owncloud.js
- src/shareManagement.js
- tests/shareRecipientTest.js
> Adding share recipient api

- README.md
- src/filesTrash.js
- src/helperFunctions.js
- src/owncloud.js
- tests/appsTest.js
- tests/capabilitiesTest.js
- tests/fileTrashTest.js
- tests/fileVersionTest.js
- tests/filesTest.js
- tests/groupTest.js
- tests/karma.js
- tests/loginTest.js
- tests/requestsOcsTest.js
- tests/shareRecipientTest.js
- tests/sharingTest.js
- tests/unauthenticated/appsTest.js
- tests/unauthenticated/capabilitiesTest.js
- tests/unauthenticated/filesTest.js
- tests/unauthenticated/groupTest.js
- tests/unauthenticated/sharingTest.js
- tests/unauthenticated/userTest.js
- tests/unauthorized/appsTest.js
- tests/unauthorized/capabilitiesTest.js
- tests/unauthorized/filesTest.js
- tests/unauthorized/groupTest.js
- tests/unauthorized/sharingTest.js
- tests/unauthorized/userTest.js
- tests/userTest.js
- move to JavaScript classes
- use Promises better
- use let and const
- new sdk initialization method
> Rework sdk:

- .drone.yml
- src/fileManagement.js
- tests/filesTest.js
- refs https://github.com/owncloud/phoenix/pull/1264
> Introduce oc.files.getPathForFileId

- src/shareManagement.js
Add `expireDate` to `Shares.shareFileWithLink()` optional params
> Extend share file with link

- src/shareManagement.js
> Expand updateShare and shareFileWithLink

- .drone.yml
- src/shareInfo.js
- src/shareManagement.js
- tests/sharingTest.js
- yarn.lock
>  no need to uft8 encode

- src/fileManagement.js
- src/publicLinkAccess.js
- tests/filesTest.js
- tests/publicLinkTest.js
- yarn.lock
Requires https://github.com/owncloud/davclient.js/pull/39/
> Add upload progress + headers

- src/shareManagement.js
- tests/sharingTest.js
> Added expiration date as optional param into shares

- .drone.yml
Make the CI happy again (https://drone.owncloud.com/owncloud/owncloud-sdk/586/1/6)
> Use PHP 7.3

- src/settings.js
Had to add 404 to the ignored error codes. Was only ignoring 502 before.
> Also ignore 404 for settings service, not just 502.

- README.md
make @DeepDiver1975 look even better
> unsquash Thomas Müller

- tests/appsTest.js
- tests/karma.js
part of #500
with this PR the status is:
``` 
Chrome Headless 85.0.4183.83 (Linux x86_64): Executed 17 of 256 (skipped 239) SUCCESS (8.284 secs / 1.134 secs)
TOTAL: 17 SUCCESS
> apps tests

- tests/capabilitiesTest.js
- tests/karma.js
Convert capabilities tests to pact.io
Part of: https://github.com/owncloud/owncloud-sdk/issues/500
> capabilities tests to pact.io

- tests/config/config.drone.json
- tests/config/config.sample.json
- tests/groupTest.js
- tests/karma.js
> convert group tests to pact.io

- .drone.star
Fix npm publish pipeline in drone.
> [Drone] Fix the npm publish pipeline in drone

- tests/config/config.drone.json
- tests/config/config.sample.json
- tests/karma.js
- tests/userTest.js
> convert some of the user tests to pact.io

- tests/config/config.drone.json
- tests/config/config.sample.json
- tests/karma.js
- tests/unauthorized/appsTest.js
This PR adds tests for unauthorized apps tests.
> AppsTest list enable and disable

- tests/signedUrlTest.js
This PR enables signedUrl tests.
> [Tests-Only]Add signedUrlTest

- tests/karma.js
- tests/unauthorized/capabilitiesTest.js
- tests/unauthorized/groupTest.js
Convert `unauthorized/capabilities.js` and `unauthorized/groupTest.js` to pact.io
part of #500
> convert unautorized capabilities tests to pact.io

- .gitignore
- tests/config/config.drone.json
- tests/config/config.sample.json
- tests/karma.js
- tests/unauthorized/sharingTest.js
> Convert unauthorized sharing tests to pact.io

- tests/karma.js
- tests/unauthorized/userTest.js
> convert some of theunauthorized userTest to pact.io

- tests/appsTest.js
- tests/config/config.drone.json
- tests/config/config.sample.json
- tests/filesTest.js
- tests/groupTest.js
- tests/karma.js
- tests/loginTest.js
- tests/sharingTest.js
- tests/unauthenticated/sharingTest.js
- tests/unauthenticated/userTest.js
- tests/unauthorized/sharingTest.js
- tests/unauthorized/userTest.js
- tests/userTest.js
This is a mindless search-replace to help my English brain when reading/reviewing test code.
> [Tests-Only] Replace 'not existing' with non-existent'

- tests/karma.js
- tests/userTest.js
https://github.com/owncloud/owncloud-sdk/issues/500
> [Tests-Only]Convert remaining user tests to pact.io

- tests/karma.js
I tried to "standardize" a bit the descriptions in the "uponReceiving" section so they read as a sentence starting with "upon receiving".
What do you think?
> [Tests-Only] Update test descriptions

- tests/karma.js
- tests/shareRecipientTest.js
##Related Issue:
- https://github.com/owncloud/owncloud-sdk/issues/500
> [Tests-Only]Convert shareRecipient test to pact.io

- tests/karma.js
- tests/sharingWithAttributesTest.js
> [Tests-Only]Convert sharing with Attributes test to pact.io

- .gitignore
- tests/config/config.drone.json
- tests/config/config.sample.json
- tests/karma.js
- tests/publicLinkTest.js
part of #500
~~blocked by https://github.com/pact-foundation/pact-js/issues/494~~
> convert public link tests to pact.io

- tests/config/config.drone.json
- tests/config/config.sample.json
- tests/karma.js
- tests/sharingTest.js
> [Tests-Only] Convert sharing test to pact.io

- tests/config/config.drone.json
- tests/config/config.sample.json
- tests/pactHelper.js
- This PR refactors the pactHelper.js to make the code DRY and maintainable. The common lines of code shared by different interactions such as response body, responseMeta etc are adjusted accordingly.
- Fixes https://github.com/owncloud/owncloud-sdk/issues/587
> [Tests-Only] Refactor PactHelper

- tests/pactHelper.js
- tests/unauthorized/filesTest.js
- Converted unauthorized filesTest to Pact.io
- Part of https://github.com/owncloud/owncloud-sdk/issues/500
> Convert unauthorized filesTest to pact.io

- tests/pactHelper.js
- tests/unauthorized/appsTest.js
With this PR:
- Included required interactions for `unauthorized/appTest.js` in the same test file
- Part of #500
> Refactore unauthorized files test to include interactions inside test file

- tests/pactHelper.js
- tests/signedUrlIntegrationTest.js
This PR adds interactions for signed url integration tests.
> [Tests-Only] Convert signed url integration tests to pact.io

- tests/config/config.drone.json
- tests/fileTrashTest.js
- tests/pactHelper.js
Convert `tests/fileTrashTest.js` to pact.io
part of #500
> [Tests-Only] Convert fileTrashTest.js to pact.io

- tests/pactHelper.js
- tests/sharingWithAttributesTest.js
This PR refactors `sharingWithAttributesTest` and adds the interactions related to sharing with attributes into the `tests/sharingWithAttributesTest.js` file.
Part of https://github.com/owncloud/owncloud-sdk/issues/500
> [Tests-Only] Refactor sharing with attributes test

- tests/capabilitiesTest.js
- tests/pactHelper.js
This PR refactors `capabilitiesTest` and adds the interactions related to capabilities into the `tests/capabilitiesTest.js` file.
Part of https://github.com/owncloud/owncloud-sdk/issues/500
> [Tests-Only] Refactor capabilities test

- tests/pactHelper.js
- tests/shareRecipientTest.js
> [Tests-Only] Interactions for share Recipient test added into shareRecipient file

- tests/pactHelper.js
- tests/requestsOcsTest.js
This PR adds the interactions related to group tests into the `tests/requestOcsTest.js` file.
- #500
> [Tests-Only] Refactor interactions for requestOcsTest file

- tests/unauthorized/filesTest.js
This PR refactors `unauthorized/filesTest.js` by changing `fit` to `it`
- #500
> [Tests-Only] Refactor interactions for unauthorized/filesTest file

- tests/groupTest.js
- tests/pactHelper.js
This PR adds tests and interaction for group creation and deletion which we previously deleted by PR https://github.com/owncloud/owncloud-sdk/pull/555/files#diff-ebd2c482509675598a2927205c5a957d60d5ac4194cd7e621962ba499696f8d5L25-L43
Part of https://github.com/owncloud/owncloud-sdk/issues/558
> [Tests-Only] Add test and interaction for group creation and deletion

- tests/fileVersionTest.js
- tests/filesTest.js
- tests/pactHelper.js
- tests/unauthorized/filesTest.js
This PR transforms all tests in `filesTest.js` to pact.io.
Related to https://github.com/owncloud/owncloud-sdk/issues/500
> [Tests-Only] Refactor file test

- tests/pactHelper.js
- tests/publicLinkTest.js
PR https://github.com/owncloud/owncloud-sdk/pull/557 converts some public share to pact.io . This PR converts the remaining tests to pact
Convert public share to pact.io
Part of #500
> [Tests-Only] Convert public share tests to pact.io

- .drone.star
- use spaces and not tabs in drone config
- use owncloudci/nodejs:12 in drone
both are preparations to make the transition to jest and pactV3 easier
> small drone fixes

- tests/pactHelper.js
- tests/requestsOcsTest.js
Import required interactions only from `pacHelper.js`
Part of https://github.com/owncloud/owncloud-sdk/issues/643
> [Tests-Only] split interactions and verify them

- tests/groupTest.js
This PR refactors the `groupTest.js` such that only the required interactions are imported. Also, verification of the requests and the interactions is done.
- Part of #643
> [Tests-Only] Verify group test

- tests/sharingWithAttributesTest.js
This PR refactors the `sharingWithAttributes.js` such that only the required interactions are imported. Also, verification of the requests and the interactions is done.
- Part of #643
> [Tests-Only] Refactor sharing with attributes test and verify it

- tests/shareRecipientTest.js
This PR refactors the share recipient test such that only the required interactions are imported. Also, verification of the requests and the interactions is done.
- Part of #643
> [Tests-Only] Verify share recipient test

- tests/capabilitiesTest.js
- tests/pactHelper.js
- tests/requestsOcsTest.js
This PR refactors the capabilities test file such that only the required interactions are imported. Also, verification of the requests and the interactions is done.
- Part of #643
> [Tests-Only]Refactor the capabilities test file to use provider verify

- tests/pactHelper.js
refactor interactions in pactHelper setGeneralInteractions to seperate functions
> [Tests-Only] refactor pactHelper setGeneralInteractions functions

- tests/pactHelper.js
- tests/signedUrlIntegrationTest.js
- tests/unauthorized/appsTest.js
- tests/unauthorized/capabilitiesTest.js
- tests/unauthorized/filesTest.js
- tests/unauthorized/groupTest.js
- tests/unauthorized/sharingTest.js
- tests/unauthorized/userTest.js
This PR refactors unauthorized tests such that only the required interactions are imported. Also, verification of the requests and the interactions is done.
- Part of #643
> [Tests-Only] Verify unauthorized tests

- tests/pactHelper.js
- tests/userTest.js
This PR refactors user test such that only the required interactions are imported. Also, verification of the requests and the interactions is done.
- Part of #643
> [Tests-Only] Verify user test

- tests/appsTest.js
- tests/fileTrashTest.js
- tests/filesTest.js
- tests/pactHelper.js
refactor of pact tests for `appTest.js` `fileTrashTest.js` and `filesTest.js`
> [Tests-Only] add provider.verify() on appTest, fileTrashTest and filesTest

- tests/publicLinkTest.js
Verify public link tests
Part of https://github.com/owncloud/owncloud-sdk/issues/643
> [Tests-Only] Verify public link tests

- tests/fileVersionTest.js
related https://github.com/owncloud/owncloud-sdk/issues/643
refactor for file version test
> [Tests-Only] add provider.verify() on file version test

- tests/sharingWithAttributesTest.js
- tests/signedUrlIntegrationTest.js
> [Tests-Only] refactor and cleanup sharingWithAttributesTest and signedUrlIntegrationTest

- tests/sharingTest.js
This PR refactors the sharing test file to use provider verify in the tests.
#643
> [Tests-Only]Test sharing refactor

- tests/fileTrashTest.js
> [Tests-Only] refactor and cleanup fileTrashTest

- tests/filesTest.js
> [Tests-Only] refactor and cleanup filesTest

- jest.config.js
- tests/groupTest.js
- tests/pactHelper.js
move group tests to jest and pactV3
there seems to be some issue with 'application/x-www-form-urlencoded' POST requests, so I ignored the body for now in POSTGroupRequest
> convert groupTests to jest and pactV3

- .gitignore
- jest.config.js
- tests/appsTest.js
move appsTest to jest and pactV3
> [Tests-Only] move appsTest to jest

- jest.config.js
- tests/pactHelper.js
- tests/userTest.js
move usersTest to jest and pactV3
> [Tests-Only] move userTest.js to jest and pactV3

- jest.config.js
- src/helperFunctions.js
- tests/unauthenticated/filesTest.js
Move unauthenticated tests to jest
- appsTest.js
- capabilitiesTest.js
- filesTest.js
- groupTest.js
- sharingTest.js
- userTest.js
> [Tests-Only] Move unauthenticated tests to jest

- jest.config.js
- tests/config/config.drone.json
- tests/config/config.sample.json
- tests/pactHelper.js
- tests/unauthorized/appsTest.js
- tests/unauthorized/capabilitiesTest.js
move unauthorized tests to jest
- appsTest
- capabilitiesTest
> [Tests-Only] move unauthorized appsTest to jest

- jest.config.js
- tests/loginTest.js
- tests/pactHelper.js
move test to jest and pactV3
- LoginTest
> [Tests-Only] move LoginTest to jest and pactv3

- jest.config.js
- tests/unauthorized/groupTest.js
move test to jest and pactV3
- unauthorized
- groupTest 
> [Tests-Only] Move unauthorized/groupTest to jest and pactV3

- jest.config.js
- tests/XmlParserTest.js
- tests/pactHelper.js
- tests/shareRecipientTest.js
- tests/sharingWithAttributesTest.js
- tests/signedUrlIntegrationTest.js
- tests/signedUrlTest.js
- signedUrl
- sharingWithAttributes
- shareReciepientTest
- signedUrlIntegrationTest
- XmlParserTest
> [Tests-Only] move signedUrl, sharingWithAttributres and shareRecipientTest to jest and pactV3

- jest.config.js
- tests/unauthorized/sharingTest.js
Move sharingTest to jest and pactV3
- unauthorized
- sharingTest
> [Tests-Only] Move unauthorized/sharingTest to jest and pactV3

- jest.config.js
- tests/unauthorized/appsTest.js
- tests/unauthorized/userTest.js
move unauthorized userTests to jest
> [Tests-Only] Convert unauthorized userTest to jest

- tests/unauthorized/userTest.js
This PR addresses review on #694
> [Tests-Only]refactor userTest

- jest.config.js
- tests/pactHelper.js
- tests/requestsOcsTest.js
- requrestOcsTest
- shareReciepentTest
> [Tests-Only] move requestOcsTest and shareRecipientTest to jest and pactv3

- jest.config.js
- jest.init.js
- package.json
- tests/pactHelper.js
- tests/sharingTest.js
- yarn.lock
> [Tests-Only] move sharing test to pactV3 and jest

- jest.config.js
- tests/pactHelper.js
- tests/publicLinkTest.js
move tests to jest and pactv3
- PublicLinkTest.js
> [Tests-Only] move publicLinkTest to pactv3 and jest

- jest.config.js
- tests/fileTrashTest.js
> [Tests-Only] move fileTrashTest to pactv3 and jest

- jest.config.js
- tests/fileVersionTest.js
move tests to jest and pactv3
- FilesVersionTest.js
> [Tests-Only] move fileVersionTest to pactv3 and jest

- jest.config.js
- src/helperFunctions.js
- tests/config/config.drone.json
- tests/config/config.sample.json
- tests/filesTest.js
- tests/pactHelper.js
> [Tests-Only] move FilesTest to pactV3 and jest

- tests/pactHelper.js
- tests/unauthorized/appsTest.js
- tests/unauthorized/groupTest.js
- tests/unauthorized/sharingTest.js
- tests/unauthorized/userTest.js
unauthorized
- appsTest
- sharingTest
- userTest
> [tests-only] Adjust pact interactions for unauthorized tests

- tests/capabilitiesTest.js
- tests/pactHelper.js
- tests/publicLinkTest.js
- tests/requestsOcsTest.js
- tests/unauthorized/appsTest.js
- tests/unauthorized/groupTest.js
- tests/userTest.js
remove all wildcard regex for ocs v1 and v2 from urls
> [Tests-Only] remove wildcard regex for ocs v1 and v2

- .drone.star
- tests/appsTest.js
- tests/capabilitiesTest.js
- tests/config/config.drone.json
- tests/config/config.sample.json
- tests/fileTrashTest.js
- tests/fileVersionTest.js
- tests/filesTest.js
- tests/groupTest.js
- tests/loginTest.js
- tests/pactHelper.js
- tests/providerTest.js
- tests/publicLinkTest.js
- tests/requestsOcsTest.js
- tests/shareRecipientTest.js
- tests/sharingTest.js
- tests/sharingWithAttributesTest.js
- tests/signedUrlIntegrationTest.js
- tests/signedUrlTest.js
- tests/unauthenticated/userTest.js
- tests/unauthorized/appsTest.js
- tests/unauthorized/capabilitiesTest.js
- tests/unauthorized/filesTest.js
- tests/unauthorized/groupTest.js
- tests/unauthorized/sharingTest.js
- tests/unauthorized/userTest.js
- tests/userTest.js
- delete unused functions
- standardise names of interaction functions
- clarify what the variables `username` and `password` are used for by renaming to `adminUsername` and `adminPassword`
- change all occurrence of hard-coded admin username to use variable from config file
> [tests-only] code cleanup

- tests/filesTest.js
- tests/pactHelper.js
- tests/providerTest.js
refactor the contract tests of the files tests to pass with oc10 provider
(skiped tests are not refactored, issue #724 is for working on those)
> refactor files tests to work on oc10 provider

- tests/providerTest.js
- tests/requestsOcsTest.js
> [tests-only] Adjust pact interactions for requestsOcsTest

- src/shareManagement.js
Make it clear that attributes can be any key value pair.
> Improve docs regarding share attributes

- tests/groupTest.js
- tests/helpers/ocsResponseParser.js
- tests/pactHelper.js
- tests/providerTest.js
- tests/userTest.js
> [tests-only] Adjust pact interactions for groupTest and userTest

- tests/pactHelper.js
- tests/unauthorized/appsTest.js
- tests/unauthorized/groupTest.js
- tests/userTest.js
both should be OK according to the RFC. See discussion in https://github.com/owncloud/ocis/issues/1686
> accept application/xml content-type where oc10 sends text/xml

- tests/helpers/sharingHelper.js
- tests/pactHelper.js
- tests/providerTest.js
- tests/publicLinkTest.js
> [tests-only] Adjust pact interaction for publicLinkTest

- tests/providerTest.js
- tests/signedUrlIntegrationTest.js
- tests/webdavHelper.js
In this PR, the signedUrlIntegration test file is adjusted such that the tests pass on the provider side as well.
- https://github.com/owncloud/owncloud-sdk/issues/709
> [Tests-Only] Adjust pact interactions for provider tests for signedUrlIntegration

- tests/pactHelper.js
- tests/sharingTest.js
- tests/sharingWithAttributesTest.js
> [tests-only] Adjust pact interactions for sharingWithAttributesTest

- tests/providerTest.js
Fixes https://github.com/owncloud/owncloud-sdk/issues/722
Remove use of Promise from `provider.given()`.
the documentation is not very clear about what is clear format, but since the `given()` function doesn't support promises, we need to remove the Promise.resolve() from return statmenets.
> [Tests-Only] Remove use of promise from sync functions

- tests/groupTest.js
> [tests-only] Adjust groupTest interactions for oCIS server

- tests/pactHelper.js
adjust interactions for oCIS
- getCurrentUserInformationInteraction
> [tests-only] Adjust loginTest interactions for oCIS server

- tests/config/config.drone.json
- tests/config/config.sample.json
- tests/pactHelper.js
- tests/userTest.js
> [tests-only] Adjust userTest interactions for oCIS

- tests/shareRecipientTest.js
- tests/sharingWithAttributesTest.js
- shareRecipientTest
- sharingWithAttributesTest
> [tests-only] Adjust shareRecipientTest and sharingWithAttributesTest interactions for oCIS

- tests/pactHelper.js
- tests/requestsOcsTest.js
> [tests-only] Adjust requestOcsTest interactions for oCIS server

- tests/config/config.drone.json
- tests/config/config.sample.json
- tests/helpers/providerStateHelper.js
- tests/helpers/sharingHelper.js
- tests/pactHelper.js
- tests/sharingTest.js
> [tests-only] Adjust pact interaction of sharingTest

- README.md
Add documentation for running pact tests
> [Docs-Only] Document how to run pact tests

- package.json
bump @pact-foundation/pact to 10.0.0-beta.33
> update pact-js to 10.0.0-beta.33

- tests/sharingTest.js
> [tests-only] Adjust sharingTest interactions for oCIS server

- tests/filesTest.js
- tests/pactHelper.js
part of #644 and #747
* fileTest
> [tests-only] Adjust fileTest  interaction for oCIS

- tests/pactHelper.js
- tests/unauthorized/groupTest.js
- tests/unauthorized/sharingTest.js
- tests/unauthorized/userTest.js
- unauthorized/groupTest
- unauthorized/sharingTest
- unauthorized/userTest
closes https://github.com/owncloud/owncloud-sdk/issues/747
> [tests-only] Adjust unauthorized tests for ocis server

- src/userManagement.js
- tests/userTest.js
same as #578 but branch-name has not `/` because that does not work in CI currently
> add enable/disable user api (no-fork)

- tests/filesTest.js
This PR 
- refactors `it('checking method: filter by tag'` so that it only tests `getFilesByTags`  and doesn't rely on  `fileInfo`, ` getFileId` `createTag`, ` tagFile` and the respected interactions
- create new tests for `fileInfo`, `createTag`, ` tagFile`
part of : https://github.com/owncloud/owncloud-sdk/issues/789
> [Tests-only] Refactor "filter by tag" test from fileTest.js 

- tests/fileTrashTest.js
- tests/fileVersionTest.js
- tests/providerTest.js
- tests/webdavHelper.js
Related - https://github.com/owncloud/owncloud-sdk/issues/780
Fix interaction for pact tests
> [Tests-Only] adjust pact interactions for fileTrash and fileVersion tests

- tests/filesTest.js
- tests/helpers/providerStateHelper.js
- tests/helpers/sharingHelper.js
- tests/pactHelper.js
- tests/sharingTest.js
- tests/webdavHelper.js
encode endpoints (file/folder path) at the end functions.
closes https://github.com/owncloud/owncloud-sdk/issues/800
> [tests-only] Encode url endpoints at the end functions

- tests/filesTest.js
- tests/helpers/providerStateHelper.js
- tests/pactHelper.js
- tests/providerTest.js
- tests/webdavHelper.js
part of https://github.com/owncloud/owncloud-sdk/issues/644 and https://github.com/owncloud/owncloud-sdk/issues/780
Adjust pact interaction for unskipped tests in filesTest.js
> [tests-only] Adjust unskipped file tests

- tests/fileTrashTest.js
- tests/filesTest.js
- yarn.lock
Fixes https://github.com/owncloud/owncloud-sdk/issues/756
Add more tests to cover files, trashbin, and favorites scenarios
> [Tests-Only] Add more files related test

- tests/publicLinkTest.js
- tests/unauthorized/filesTest.js
part of https://github.com/owncloud/owncloud-sdk/issues/644 and https://github.com/owncloud/owncloud-sdk/issues/780
- publiLinkTest
- unauthorized/filesTest
> [tests-only] Adjust interactions of publiLink and unauthorized/files tests for ocis

- tests/filesTest.js
part of https://github.com/owncloud/owncloud-sdk/issues/644 and https://github.com/owncloud/owncloud-sdk/issues/780
- filesTest
> [tests-only] Adjust pact interactions for oCIS server

- README.md
With this PR:
- added how to add tests in docs
Closes https://github.com/owncloud/owncloud-sdk/issues/802
> [Tests-Only]Improve test docs

- tests/helpers/webdavHelper.js
- tests/providerTest.js
With this PR:
- code DRY for environment vars used
- spell fixes
> [Tests-Only] simple refactorings and spell fixes

- .drone.env
- .drone.star
- tests/providerTest.js
changes:
- change storage driver to `ocis`
- revert changes made in https://github.com/owncloud/owncloud-sdk/pull/755
- bump ocis commit-id
Closes https://github.com/owncloud/owncloud-sdk/issues/834
> [tests-only] Change ocis storage driver from owncloud to ocis

- src/helperFunctions.js
Reverts owncloud/owncloud-sdk#855
> Revert "Prevent owncloud-sdk from modifying global axios interceptors and cleanup upon logout"

- src/helperFunctions.js
Reverts owncloud/owncloud-sdk#868 / Re-introduces #855 because it's actually a neat improvement
> Revert "Revert "Prevent owncloud-sdk from modifying global axios interceptors and cleanup upon logout""

- tests/filesTest.js
Remove outdated issue tag from the tests
Fixes https://github.com/owncloud/owncloud-sdk/issues/860
> [Tests-Only] remove issue link from the tests that has been fixed

- package.json
- yarn.lock
> Remove xmldom from dependencies

- src/filesTrash.js
I forgot that besides listing the recycle, users might also want to "restore"... Who knew...
> Query parameters for all recycle functions

- changelog/unreleased/enhancement-share-spaces
- src/shareManagement.js
Implement the `space_ref` param according to https://github.com/cs3org/reva/pull/2622.
Needed for https://github.com/owncloud/web/pull/6577/files.
> Add the 'space_ref' param to the share management

- tests/filesTest.js
depth 2 with PROPFIND is not a valid thing in WebDAV, so delete the test
> [tests-only] delete test for PROPFIND depth 2

- .drone.star
report nightly build status in build channel of owncloud rocket chat
> [tests-only]notify build status in rocket chat

- changelog/unreleased/enhancement-add-move-overwrite-flag
- src/fileManagement.js
We've added an overwrite flag for the file move operation
> Add overwrite flag for move

- .drone.env
- .drone.star
- tests/capabilitiesTest.js
- tests/filesTest.js
- tests/helpers/pactHelper.js
- tests/helpers/userHelper.js
- tests/unauthorized/filesTest.js
Remove passing tests out of pending state
Part of https://github.com/owncloud/owncloud-sdk/issues/1089
> [tests-only] Remove passing tests from pending state (1)

- changelog/unreleased/enhancement-add-copy-overwrite-flag
- src/fileManagement.js
We've added an overwrite flag for the file copy operation
> Enhancement: Add overwrite flag for file copy

- tests/fileTrashTest.js
- tests/fileVersionTest.js
- tests/helpers/pactHelper.js
- tests/loginTest.js
- tests/requestsOcsTest.js
- tests/shareRecipientTest.js
- tests/signedUrlIntegrationTest.js
Remove passing tests out of pending state
Part of https://github.com/owncloud/owncloud-sdk/issues/1089
> [tests-only] Remove passing tests from pending state (2)

- .drone.env
- .drone.star
beside bumping the commit ID, new version of go needed to be used
> bump ocis commit id

- changelog/unreleased/enhancement-add-range-to-search-result
- src/fileManagement.js
- src/helperFunctions.js
- tests/filesTest.js
Enhancement: Add range to search result
We've added the range property to the search result, so we can retrieve the found items,
even if the search limit will be exceeded.
> Add range to search response

- .drone.env
Bumps ocis commit for tests
Signed-off-by: Kiran Parajuli <kiranparajuli589@gmail.com>
> [full-ci][tests-only] bump ocis commit id for tests

- .drone.env
Part of : https://github.com/owncloud/QA/issues/763
> [tests-only][full-ci]Bump Ocis commit

- .drone.env
Bump ocis commit id to the latest for the tests
Part of https://github.com/owncloud/QA/issues/766
> [tests-only] Bump ocis commitid

- .drone.env
Part of: https://github.com/owncloud/QA/issues/766
> [tests-only] Bump ocis commit id for tests

- .drone.env
- .drone.star
Bump ocis commit id to latest.
Part of https://github.com/owncloud/QA/issues/768
> [full-ci] [tests-only] Bump ocis commit id to latest

- .drone.env
This PR bumps the ocis commit id for tests
part of: https://github.com/owncloud/QA/issues/782
> [tests-only][full-ci] Bump commit id for tests

- .drone.star
Same as https://github.com/owncloud/owncloud-sdk/pull/1190 but for `stable-3.0`.
> use default workspace path

- .drone.env
Bump oCIS commit id for the tests
Part of https://github.com/owncloud/QA/issues/785
> [tests-only] Bump oCIS commit id

- .drone.env
Bump latest `ocis-master` commit-id
https://github.com/owncloud/QA/issues/791
> [tests-only]Bump latest ocis commit to sdk

- .drone.env
Part of https://github.com/owncloud/QA/issues/795
> [tests-only] [full-ci] Bump ocis master commit id to latest

- src/shareManagement.js
Adds `shareWithUser` and `shareWithProvider` to `optionalParams`
> ocm: add shares params

- .drone.env
- .drone.star
Part of: https://github.com/owncloud/QA/issues/803
> [tests-only][full-ci]Bump commit id for tests

- changelog/unreleased/bugfix-add-missing-headers
- src/fileVersionManagement.js
- src/helperFunctions.js
Required for https://github.com/owncloud/web/issues/8612.
> Add missing headers from init()

- .drone.env
Part of: https://github.com/owncloud/QA/issues/805
> [full-ci][tests-only]Bump ocis commit id

- .drone.env
- .drone.star
Bump latest ocis commit id to owncloud sdk.
https://github.com/owncloud/QA/issues/805
> [tests-only]Bump latest ocis master commit

- .drone.env
bump latest ocis master commit to owncloud-sdk
https://github.com/owncloud/QA/issues/807
> Bump latest ocis commit to sdk

- changelog/unreleased/enhancement-add-ocs-error
- src/OCSError.js
- src/helperFunctions.js
- tests/appsTest.js
- tests/loginTest.js
- tests/sharingTest.js
- tests/unauthorized/appsTest.js
- tests/unauthorized/capabilitiesTest.js
- tests/unauthorized/filesTest.js
- tests/unauthorized/groupTest.js
- tests/unauthorized/sharingTest.js
- tests/unauthorized/userTest.js
- tests/userTest.js
Adding OCSError containing:
* message
* response (that's important for having x-request-id accessible)
* ocs (ocs meta data)
> [full-ci] Add OCSError

- .drone.env
Part of: https://github.com/owncloud/QA/issues/827
> [tests-only] bump latest ocis commit id

- .drone.env
bump ocis commit id for tests
part of https://github.com/owncloud/QA/issues/834
> [full-ci][tests-only] bump ocis commit-id

- .drone.env
part of: https://github.com/owncloud/QA/issues/838
> [tests-only][full-ci]tests: bump ocis commit id for tests

- .drone.env
part of: https://github.com/owncloud/QA/issues/838
> [tests-only][full-ci]test: bump ocis commit id for tests

- .drone.env
Bump ocis to latest commit id
Part of https://github.com/owncloud/QA/issues/839
> bump ocis commit-id

- .drone.env
Part of https://github.com/owncloud/QA/issues/839
> [full-ci] [tests-only] Bump ocis commit id

- .drone.env
- tests/helpers/pactHelper.js
This PR is part of https://github.com/owncloud/QA/issues/840
> [tests-only][full-ci] Bump ocis commit id
