owncloud/owncloud-sdk

- owncloud/owncloud.js
this allows access to helper functions like _makeOCSRequest - which is really handy.
We might even think to expose this fundtion and other helpers directly ....
> Expose helpers class in owncloud client

- .travis.yml
- Makefile
- karma.conf.js
- package.json
- tests/karma.js
- webpack.config.js
- yarn.lock
code coverage is now generated and pushed to codecov.io
> Add codecoverage

- src/owncloud.js
- tests/requestsOcsTest.js
This allows to use a body in a oc.requests.ocs. Body as of is always content-type json
> Fix requests with body and set proper cors mode in fetch requests

- src/fileManagement.js
A propfind for a file was sent to the path /remote.php/webdav/123.jpeg/
In some setups such a trailing slash will result in a 404
> No need to append a / at the end of the path before doing a propfind

- src/shareManagement.js
```js
// get all accepted shares of the current user on the file 'lorem.txt'
oc.shares.getShares('lorem.txt', {"share_with_me": true, state: 0}
// get all pending shares of the current user on the file 'lorem.txt'
oc.shares.getShares('lorem.txt', {"share_with_me": true, state: 1}
// get all declined shares of the current user on the file 'lorem.txt'
oc.shares.getShares('lorem.txt', {"share_with_me": true, state: 2}
```
I'm open to discuss if we shall rework the options.
e.g. 
- use shaewWithMe to follow proper naming conventions
- use constants instead of magic numbes
> Add state parameter on getShares

- src/shareManagement.js
`updateShare()` now accepts empty strings as valid input, to be able to remove set values from a share.
> updateShare accepts empty password and expireDate

- .drone.yml
- src/helperFunctions.js
- tests/capabilitiesTest.js
When we got response in XML format the booleans were translated into string which caused desync between oc and reva.
@refs
> Add json format to capabilities request

- src/shareManagement.js
Currently, creating a public link share with empty name is possible, but updateShare ignores name parameter when its empty. 
This pr fixes that behavior and allows updating a link share with empty name.
> allow empty share name when updating shares

- karma.conf.js
- package.json
- src/fileInfo.js
- src/fileManagement.js
- src/helperFunctions.js
- tests/filesTest.js
- yarn.lock
Whenever a list() or fileInfo() call response contains TUS headers,
return these through the fileInfo.getTusSupport() method.
If no TUS headers are found, that method returns null.
Fixes https://github.com/owncloud/owncloud-sdk/issues/458
> Add TUS support information on FileInfo object

- src/publicLinkAccess.js
- tests/publicLinkTest.js
In my prev PR (#437) I separated in the list method in publicAccess the token and path. However, this brings more complexity where it's being used since we might need to take care of separating those two then. By uniting them again we save effort on the client side.
> Merged token and path in public list and fileinfo

- .drone.yml
The older docker image has out-of-date codecov upload scripts.
Similar to https://github.com/owncloud/core/pull/37416
> Use plugins/codecov:latest

- src/settings.js
For technical reasons the api response is `undefined` instead of
an empty array when there are no settings values for the given user.
We want to provide an empty array instead, so that consumers of the
SDK can rely on dealing with a valid list (which is empty).
> Return empty array when listing of settings values is empty

- src/shareManagement.js
In oCIS, a string is a valid share id.
> Do not reject share promises if the id is a string

- .drone.yml
- package.json
- src/helperFunctions.js
- src/owncloud.js
- tests/signedUrlIntegrationTest.js
- tests/signedUrlTest.js
- yarn.lock
This introduces url signing for owncloud - starting to be shipped as of 10.6(?)
```javascript
// get an absolute url to a file - will work with webdav v1 as well
const url = oc.files.getFileUrlV2('/file.txt')
// sign the url - optional parameters are ttl and httpMethod
const signedUrl = await oc.signUrl(url)
// a simple fetch without additional headers can be done using the signed url
const response = await fetch(signedUrl)
expect(response.ok).toEqual(true)
const txt = await response.text()
> Integrate owncloud-sign-url

- codecov.yml
- src/settings.js
- vendor/settingsClient.js
When [this ocis-settings PR](https://github.com/owncloud/ocis-settings/pull/46) gets merged the api call for listing settings values will require a different param nesting (`identifier` doesn't exist anymore, `account_uuid` is on highest level now).
Since the settings are not in production anywhere just yet, we can already merge this, so that a PR in phoenix can be prepared.
Also, there was a nasty bug when the settings service is not available: `error.response.status` was not accessible and threw an error. Fixed this by checking first if a response exists at all.
> Adapt request to settings service to new API endpoint params

- README.md
- src/userManagement.js
- tests/userTest.js
As discussed with @LukasHirt 
https://talk.owncloud.com/group/aarnet-tech?msg=c2wy8KRkF4tQseMh4
This SDK is missing the `groups` parameter - this enables subadmin users of a specific group to create more users in that group, which was not previously possible via this API.
> Add missing groups parameter to createUser API

- tests/config/config.drone.json
- tests/config/config.sample.json
- tests/filesTest.js
- tests/karma.js
part of #500 
~~blocked by https://github.com/pact-foundation/pact-js/issues/494~~
~~should be unblocked by https://github.com/pact-foundation/pact-js/pull/495~~
convert MKCOL tests to pact.io
the diff looks strange because I've deleted one `OPTIONS` request and made the main `OPTIONS` request more general
> convert MKCOL tests to pact.io

- tests/pactHelper.js
- tests/sharingTest.js
New interactions and the interactions previously added in the pactHelper related to authorized sharing are added in the sharing tests file.
- https://github.com/owncloud/owncloud-sdk/issues/500#issuecomment-701138139
> [Tests-Only] Add interactions for the tests in sharing tests

- tests/fileVersionTest.js
- tests/pactHelper.js
This PR refactors `fileVersionTest.js` to use pact.io and adds the interactions related to file versions into the tests/fileVersionTest.js file.
Part of https://github.com/owncloud/owncloud-sdk/issues/500
> [Tests-Only] Refactor fileVersionTest to use pact.io

- src/owncloud-sign-url/src/signUrl.js
- src/owncloud-sign-url/src/utils.js
- tests/owncloud-sign-url/signUrlTest.js
This PR
1. matches the hashed key in `signed url generator` and `signed url verifier` . Because of https://github.com/owncloud/owncloud-sdk/pull/616, hashed key doesn't match in `generateSignedUrl` and `verifySignedUrl` function
2. runs `owncloud-sign-url/signUrlTest.js`
- On top of https://github.com/owncloud/owncloud-sdk/pull/616
- Part of https://github.com/owncloud/owncloud-sdk/issues/500
> [Tests-Only] Run sign url test

- tests/appsTest.js
- tests/capabilitiesTest.js
- tests/fileTrashTest.js
- tests/fileVersionTest.js
- tests/filesTest.js
- tests/groupTest.js
- tests/loginTest.js
- tests/owncloud-sign-url/signUrlTest.js
- tests/publicLinkTest.js
- tests/requestsOcsTest.js
- tests/shareRecipientTest.js
- tests/sharingTest.js
- tests/sharingWithAttributesTest.js
- tests/signedUrlIntegrationTest.js
- tests/signedUrlTest.js
- tests/unauthorized/appsTest.js
- tests/unauthorized/capabilitiesTest.js
- tests/unauthorized/filesTest.js
- tests/unauthorized/groupTest.js
- tests/unauthorized/sharingTest.js
- tests/unauthorized/userTest.js
- tests/userTest.js
Since we have converted all the tests to pact.io, there's no need for a focused describe `fdescribe`. So, this PR converts all the `fdescribe`s to `describe`
#500
> [Tests-Only] Convert fdescribe to describe

- package.json
- src/fileManagement.js
- src/helperFunctions.js
- tests/loginTest.js
- tests/unauthorized/appsTest.js
- tests/unauthorized/capabilitiesTest.js
- tests/unauthorized/groupTest.js
- tests/unauthorized/sharingTest.js
- tests/unauthorized/userTest.js
- yarn.lock
move from https://github.com/iriscouch/browser-request to https://github.com/lquixada/cross-fetch
reasons:
1. browser-request seems not to be maintained anymore
2. to be able to switch the tests to jest, to run jest with pact-io we need to run it in node mode and `browser-request` does not support that
`Unauthorised` vs. `Unauthorized`
the HTTP response text for `401` is `Unauthorized` (`browser-request` seem to have returned
`Unauthorised`) but the OCS status response is `Unauthorised`, so in the tests we have mixed expectations
```
curl http://localhost/owncloud-core/ocs/v1.php/cloud/apps -v
*   Trying 127.0.0.1:80...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 80 (#0)
> GET /owncloud-core/ocs/v1.php/cloud/apps HTTP/1.1
> Host: localhost
> User-Agent: curl/7.68.0
> …
```
> move from browser-request to cross-fetch

- .drone.star
- tests/appsTest.js
- tests/capabilitiesTest.js
- tests/fileVersionTest.js
- tests/pactHelper.js
- tests/requestsOcsTest.js
1. Add pactLog step in CI for showing pactio log files
2. Remove callbacks from the test hook functions (beforeAll, afterAll, beforeEach, afterEach)
3. use createOwncloud() function from `pacthelper` to create new instance of owncloud sdk
> Refactor appsTests and capabilitiesTest

- tests/unauthorized/appsTest.js
- tests/unauthorized/capabilitiesTest.js
- tests/unauthorized/filesTest.js
- tests/unauthorized/groupTest.js
- tests/unauthorized/sharingTest.js
- tests/unauthorized/userTest.js
> Refactor and cleanup unauthorized tests

- tests/groupTest.js
- tests/loginTest.js
- tests/userTest.js
> [Tests-Only] cleanup and refactor groupTest, loginTest and UserTest

- tests/publicLinkTest.js
- tests/requestsOcsTest.js
- tests/shareRecipientTest.js
> [Tests-Only] refactor and cleanup publicLinkTest requestOcsTest shareRecipientTest

- tests/pactHelper.js
- tests/sharingTest.js
Reason: currently we run the tests on browser runtime.
so it makes a cors request
Because of that verify() will throw error because the cors request will not be called sometime
This maybe because the browser runtime caches the cors info
We will have to add that when the tests are moved to jest. Because jest runs in node runtime and probably will not make the OPTIONS requests
> [Tests-Only] remove provider.verify() call

- tests/fileVersionTest.js
- tests/publicLinkTest.js
> [Tests-Only] refactor and cleanup fileVersionTest and publicLinkTest

- package.json
- tests/pactHelper.js
- tests/sharingTest.js
- tests/sharingWithAttributesTest.js
- tests/userTest.js
- yarn.lock
these tests have been incomplete and the body part was ignored because of a bug in pact-js see https://github.com/pact-foundation/pact-js/issues/577
as the bug is fixed now, we can bring back these bodies
note: the issue in `signedUrlIntegrationTest.js` seems to be an other one, looking into that now
> [tests-only] fix tests that use x-www-form-urlencoded body

- tests/signedUrlIntegrationTest.js
the linked issue is a bit different to what we see here
this PR should fix it: https://github.com/pact-foundation/pact-js/pull/590
- fix content type of response
- fix comment about the issue in the test response
> [tests-only] fix comments about issues in txt response

- .drone.star
- jest.config.js
- package.json
- tests/appsTest.js
- tests/capabilitiesTest.js
- tests/groupTest.js
- tests/pactHelper.js
- tests/providerTest.js
- yarn.lock
part of #644 
fixes #647
This PR is the start to run the existing pact tests against oC10 as provider
1. adjust some tests so that they pass on the provider
2. create pact states (given ...) to setup and delete groups - because we cannot have currently async code in the state handlers I'm using the `sync-fetch` library for that
3. setup and run provider tests in drone with oc10
- run consumer tests: `rm tests/pacts/owncloud-sdk-oc-server.json ; yarn run test-consumer`
- run provider tests: `PROVIDER_BASE_URL=http://localhost/owncloud-core yarn test-provider`
the local test run will currently fail because there are still a lot of interaction that are not correct (e.g. CORS) and other interactions have missing given steps.
To run only a subset of tests reduce the `testMatch` in …
> provider tests run in drone with oc10

- package.json
- tests/filesTest.js
- tests/pactHelper.js
- tests/signedUrlIntegrationTest.js
- yarn.lock
these checks were skipped because of a bug in pact-js (https://github.com/pact-foundation/pact-js/pull/590)
after the bug got fixed and a new version released we can enable them again
> update pact.js & fix tests that were skipped because of a pact bug

- tests/filesTest.js
- tests/pactHelper.js
- tests/providerTest.js
- tests/webdavHelper.js
1. get rid of unneeded CORS headers
2. use matchers for etag and file ids
3. create states for creating files & folders
this is part of #709
> [tests-only] some fixes to make more files tests pass in the provider

- package.json
- yarn.lock
a new version of pact-js was published
Features
fix file locking, add 'overwrite' and 'callbackTimeout' flags (e891fcc), closes #599 #600
Fixes and Improvements
make the callback timeout configurable with a 5 sec default (a0f0876)
> update pact-js to 10.0.0-beta.30

- .drone.star
- tests/appsTest.js
- tests/capabilitiesTest.js
- tests/fileTrashTest.js
- tests/fileVersionTest.js
- tests/filesTest.js
- tests/groupTest.js
- tests/pactHelper.js
- tests/providerTest.js
- tests/publicLinkTest.js
- tests/requestsOcsTest.js
- tests/shareRecipientTest.js
- tests/sharingTest.js
- tests/sharingWithAttributesTest.js
- tests/signedUrlIntegrationTest.js
- tests/userTest.js
- tests/webdavHelper.js
In order to be able to test the interactions that create or delete folders this PR makes some general changes
- renaming authHeader variables to make it clear that those are admin auth
- new state to recreate (delete and create again) a user
- runs create/delete folder tests as `testUser`
- recreates the `testUser` in provider tests
> adjust create/delete folder tests to pass on oc10 provider

- package.json
- tests/pactHelper.js
- tests/sharingTest.js
- yarn.lock
- update pact-js to 10.0.0-beta.31
- remove hacks that were added because of char encoding bug in pact
see https://github.com/pact-foundation/pact-js/issues/589
> revert hacks that were introduced because of char encoding bug in pact

- jest.config.js
just run all test files, no need to list them one-by-one. Some files got forgotten
Now running 251 tests vs 237 before
> run all tests

- src/shareManagement.js
- tests/config/config.drone.json
- tests/config/config.sample.json
- tests/shareRecipientTest.js
In this PR, the share recipient test file is adjusted such that the tests pass on the provider side as well.
- https://github.com/owncloud/owncloud-sdk/issues/709
- https://github.com/owncloud/core/issues/38397
> [Tests-Only] Adjust pact interactions for provider tests for shareRecepient

- package.json
- tests/fileVersionTest.js
- tests/providerTest.js
- tests/webdavHelper.js
- yarn.lock
part of #709
- fix matcher to be correct V3Matcher function call
- delete unneeded checks
- delete access control headers
- don't delete created file after tests
- make fileVersions tests to work with oc10 provider
> modify files versions tests to pass with oC10 provider

- .drone.env
- .drone.star
- tests/providerTest.js
- create a user with email address, as it is required in OCIS. 
- after recreating the user make an extra requests to have a workaround for  owncloud/ocis#1675
- on ocis skip the provider state that makes users subadmins of groups see https://github.com/owncloud/product/issues/289
- run the tests in drone and upload to pactflow
next step (in other PRs) will be to make as much test pass as possible and raise issues for the other ones
> run provider tests in ocis

- .drone.star
with the current V3 version of pact we don't write a logfile, so this step is not needed as pointed out by @dpakach in https://github.com/owncloud/owncloud-sdk/pull/740#discussion_r579090880
> remove pact log step from drone

- tests/providerTest.js
pact-js 10.x (using pact V3) does not use (yet) `consumerVersionSelectors` but `consumerVersionTags` see https://github.com/pact-foundation/pact-js/blob/feat/v3.0.0/src/v3/verifier.ts
> use consumerVersionTags option instead of consumerVersionSelectors

- tests/pactHelper.js
some previously passed tests are failing because of content-type mismatch
fixes https://github.com/owncloud/owncloud-sdk/issues/745
> [tests-only ] Fix content-type in tests

- tests/appsTest.js
- tests/capabilitiesTest.js
- tests/fileTrashTest.js
- tests/fileVersionTest.js
- tests/filesTest.js
- tests/groupTest.js
- tests/pactHelper.js
- tests/publicLinkTest.js
- tests/requestsOcsTest.js
- tests/shareRecipientTest.js
- tests/sharingTest.js
- tests/sharingWithAttributesTest.js
- tests/signedUrlIntegrationTest.js
- tests/unauthorized/appsTest.js
- tests/unauthorized/filesTest.js
- tests/unauthorized/groupTest.js
- tests/unauthorized/sharingTest.js
- tests/unauthorized/userTest.js
- tests/userTest.js
This PR makes pact interaction names more consistent
All interaction names follow the same pattern i.e. `.uponReceiving(a <METHOD> request ...)`
closes https://github.com/owncloud/owncloud-sdk/issues/723
> [tests-only] Consistent interaction names

- tests/userTest.js
`userTest` had `username` variable within the interaction functions because of which the interaction names were unexpected
like `as 'nonExistingUser' ...` which should not be.
This PR fixes that issue
> [tests-only] fix username conflict in userTest

- .drone.star
This PR removes line/step to set skeleton directory in owncloud server config.
Skeleton files are not needed for the tests and preventing skeleton files from being created for each user creation will make the test run-time faster (testing against owncloud10).
Also removes other unnecessary configs
> [tests-only] Do not set skeleton directory in CI

- tests/config/config.drone.json
- tests/config/config.sample.json
- tests/fileTrashTest.js
- tests/fileVersionTest.js
- tests/filesTest.js
- tests/loginTest.js
- tests/pactHelper.js
- tests/publicLinkTest.js
- tests/signedUrlTest.js
- tests/unauthenticated/appsTest.js
- tests/unauthenticated/capabilitiesTest.js
- tests/unauthenticated/filesTest.js
- tests/unauthenticated/groupTest.js
- tests/unauthenticated/sharingTest.js
- tests/unauthenticated/userTest.js
Fixes https://github.com/owncloud/owncloud-sdk/issues/757
> [Tests-Only] Refactor backendHost and pact port config for pact tests

- tests/config/config.sample.json
the URL needs a trailing slash otherwise the tests cannot create correct path e.g. `Expected: "http://127.0.0.1:1234remote.php/dav/public-files/abcdef/foo/bar.txt"`
> add trailing slash for backendHost in example config

- tests/config/config.drone.json
- tests/config/config.sample.json
- tests/fileTrashTest.js
- tests/fileVersionTest.js
- tests/filesTest.js
- tests/loginTest.js
- tests/pactHelper.js
- tests/publicLinkTest.js
- tests/signedUrlTest.js
- tests/unauthenticated/appsTest.js
- tests/unauthenticated/capabilitiesTest.js
- tests/unauthenticated/filesTest.js
- tests/unauthenticated/groupTest.js
- tests/unauthenticated/sharingTest.js
- tests/unauthenticated/userTest.js
Fixes https://github.com/owncloud/owncloud-sdk/issues/775
> [tests-only]Refactor backendHost and pactMockPort to get complete URL

- tests/appsTest.js
This PR adjusts the test to disable app when app exists by deleting the re-enabling part.
- https://github.com/owncloud/owncloud-sdk/issues/790
> [Tests-Only]Splits test for disable app when app exists

- tests/helpers/providerStateHelper.js
- tests/helpers/sharingHelper.js
- tests/providerTest.js
- tests/publicLinkTest.js
- tests/sharingTest.js
This PR refactors `sharingHelper` and `providerStateHelper` functions to be more flexible and modular
- each function for each share (user, group, public)
- includes possible share options
closes https://github.com/owncloud/owncloud-sdk/issues/786
> [tests-only] Make sharing and providerState helper functions modular/flexible

- .drone.star
- tests/providerTest.js
In oCIS, deleting users via API doesn't delete the user's data directory.
When recreating deleted user, previously added files/folders are also restored, which causes unexpected failures in oCIS provider tests.
This PR aims to cleanup the user's data directory every time before the user is recreated.
POC https://drone.owncloud.com/owncloud/owncloud-sdk/2275/2/8 (L:73, L:115)
Closes https://github.com/owncloud/owncloud-sdk/issues/814
> [tests-only] Delete user data directory when testing against oCIS server

- package.json
- src/helperFunctions.js
- src/publicLinkAccess.js
- yarn.lock
update axios version to 0.21.1
Fix related issues with the new version
- After updating the webdav client in https://github.com/owncloud/owncloud-sdk/pull/735 (which also uses Axios in the backend), the request interceptor which was already in place (to add the authtoken in every request) also kicks in for the dav requests.
While this is ok for regular file operations, in public link, this creates a problem since public link uses different form of auth ( eg. public:password). That was fixed in this PR
- The auth headers were added in two different forms (`authorization` and `Authorization`). Because of this, after the request interceptor adds new header the actual header sent were in the form `Authorization: Bearer <token>, Bearer <token>`
This pr changes all auth headers to …
> Update axios version to 0.21.1

- .drone.star
CI would fail if the branch name has `/` in it like `dev/fix-bugs`. 
The issue was with
```bash
curl -XPUT -H"Content-Type: application/json" -H"Authorization: Bearer $${PACTFLOW_TOKEN}" \
https://jankaritech.pactflow.io/pacticipants/owncloud-sdk/versions/$${DRONE_COMMIT_SHA}/tags/$${DRONE_SOURCE_BRANCH}
```
here `DRONE_SOURCE_BRANCH` is used in a URL. So having `/` in a branch-name would break the endpoint
Fixes https://github.com/owncloud/owncloud-sdk/issues/764
> [tests-only] Sanitize branch name in drone CI

- package.json
- tests/appsTest.js
- tests/capabilitiesTest.js
- tests/fileTrashTest.js
- tests/fileVersionTest.js
- tests/filesTest.js
- tests/groupTest.js
- tests/helpers/pactHelper.js
- tests/publicLinkTest.js
- tests/sharingTest.js
- tests/sharingWithAttributesTest.js
- tests/signedUrlIntegrationTest.js
- tests/userTest.js
- yarn.lock
Bump pact-js to 10.0.0-beta.36
- Use matchers  in XmlBuilder instead of string literals
> Bump pact-js to 10.0.0-beta.36

- src/helperFunctions.js
Found two other instances of `reject`s without `return`s. Doesn't hurt to add them I guess...
> Return early on rejected promises

- src/dav.js
- src/filesTrash.js
- src/helperFunctions.js
We implemented the recycle bin of our EOS projects with a query parameter. This was discussed with the OCIS backend team and they will use the same way to return the recycle of spaces.
The `webdav` client encodes the path, unless if we manually set `url` in the request options. In this PR I generate the URL in the SDK instead of relying in the library.
What do you think?
Btw, to set the recycle query param we just set as the url... We could provide an extra option in this function call if you prefer.
> Use custom url to avoid encoded by the webdav library

- src/dav.js
Without this change a TypeError is caused inside the Promise that completely breaks it.
It does not succeed and does not reject, it just breaks when there is no response data available.
This happens for CONNECTION_REFUSED errors and I can imagine this might happen as well with CORS errors.
With this change the original response can be accessed and no body or status are available (because that's what those failed requests look like to javascript)
> Only use response data/status when available in dav.request

- src/settings.js
- vendor/settingsClient.js
This PR hardcodes the axios instance from the helperFunctions.js (already has auth headers injected) to be used in the settings client. Added a comment about code generation and manual changes in the `settingsClient.js` to raise awareness.
This is needed if we ever want to bump the sdk in `github.com/owncloud/web` and stay compatible with the current ocis settings implementation.
If you want to test this with an ocis instance (I did), you can create a local link to the owncloud sdk in web, build web, then start ocis with web assets from your build, and check if the language gets correctly fetched from the backend on initial page load (i.e. switch language to non-default in the settings ui, go back to the files app, reload page).
> Fix settings listing

- package.json
- src/dav.js
- src/fileManagement.js
- src/fileVersionManagement.js
- src/filesTrash.js
- src/helperFunctions.js
- src/publicLinkAccess.js
- src/systemTags.js
- tests/fileTrashTest.js
- tests/filesTest.js
- tests/helpers/pactHelper.js
- tests/parseClarkNotationTest.js
- tests/signedUrlIntegrationTest.js
- tests/unauthenticated/filesTest.js
- tests/unauthorized/filesTest.js
- yarn.lock
fixes https://github.com/owncloud/owncloud-sdk/issues/958
> Change to webDavV2 + cleanup

- changelog/unreleased/change-drop-ie-support
Technically this was already part of the `1.1.1` release, but better now than never 😬
> Add changelog for dropping IE support

- src/owncloud.js
Calling the capabilities endpoint is expensive. When running in CERNBox it's extremely expensive...
Since in Web we call `login()` and `getCapabilities()` one after the other, I don't see a reason to do 2 requests.
In this PR I create a cache that stores the latest retrieved value. From the web I will set `refresh` as `false`.
I implemented this way to keep the same behavior by default, but maybe the login could also take it in consideration (in case in the future we switch the order and call `getCapabilities()` first.
Let me know if you agree with this or if you prefer something else.
> Cache getCapabilities

- changelog/1.1.2_2022-02-01/bugfix-ocs-reject
- src/helperFunctions.js
Same as #977 but without the version bump to v1.1.2 (because master already is at v2.0.0-alpha.x).
> Reject promise when network request fails in OCS

- README.md
- changelog/unreleased/change-peerdependencies
- package.json
Suggestion to align the used versions of named packages (for the `filepicker` and `web`) and reduce the bundle size (e.g. currently, `web` ships with two different axios versions in its bundle)
Fixes #972 
~Please don't merge, we'll have to test for capability of version ranges first~ should be good to go since https://github.com/owncloud/web/pull/6287 has a green web CI with the previous breaking changes
> Change: Move dependencies to peerDependencies

- src/filesTrash.js
Remove no longer needed dav version option
Looks like if you removed one extra line (and one less) when removing the old dav endpoints.
(ping @pascalwengerter @kulmann)
> Restore query parameters on recycle list

- changelog/unreleased/bugfix-x-requested-with-header
- src/helperFunctions.js
oC 10 uses this header to determine whether a request is an ajax
request. If we want to get rid of this, we need to make sure it's
not used anymore. For example currently it's used to determine
whether a PROPFIND on a password protected link should show
an auth popup or not.
Needed to fix https://github.com/owncloud/web/issues/5727
> Add X-Requested-With header to all requests

- changelog/unreleased/change-files-trash-pass-full-path copy
- src/filesTrash.js
- tests/fileTrashTest.js
- yarn.lock
Change: Pass full trash bin path to methods of FilesTrash class
Since incompatibility with spaces, we changed the way how the methods of the class
FilesTrash(filesTrash.js) need to be called.
Now it is mandatory to pass the full webDav(v2) path of the trash bin.
> Require path for FilesTrash bin class

- changelog/unreleased/enhancement-resolve-type-blob
- src/helperFunctions.js
`arrayBuffer` can be converted to a blob, but no need to do that, when we can retrieve it directly and the change is quite minimal.
> Add handling for additional responseType 'blob'

- changelog/unreleased/enhancement-share-spaces
- src/shareManagement.js
In addition to https://github.com/owncloud/owncloud-sdk/pull/1025
Also moved the `space_ref` param for the user sharing to post params to keep that consistent with the rest. It's the preferred way for the backend as I found out.
> Add the space_ref param for link- and user-shares

- .drone.env
- .drone.star
- tests/helpers/webdavHelper.js
- tests/providerTest.js
> Bump oCIS commit id

- .drone.star
the commitid was ignored and the top of master was always used
> use also commit id of ocis when running tests

- .eslintrc.json
- changelog/unreleased/enhancement-quicklink
- jest.config.js
- src/shareManagement.js
- tests/shareManagement.spec.js
[#2715](https://github.com/cs3org/reva/pull/2715) introduced a new link variant which only can exist once per resource, this is needed for [6605](https://github.com/owncloud/web/issues/6605).
> Respect optional quicklink param for shareFileWithLink

- .drone.star
using the nightly build might be dangerous and is not needed, better to test against the version we would really use the SDK with
> [tests-only] use latests as OC10 version

- changelog/unreleased/enhancement-send-oc-etag
- src/fileManagement.js
Enhancement: send oc-etag on putFileContents and getFileContents methods
Due to server encoding, the ETag might differ from OC-ETag, therefore we emit both.
> Emit OC-Etag

- .drone.star
- tests/filesTest.js
- tests/helpers/webdavHelper.js
This PR removes tests related to depth `infinity` and also set to `dav.propfind.depth_infinity` is removed from CI as OC 10.10 by default does not allow to request depth=infinity in PROPFIND
Part of this issue : https://github.com/owncloud/web/issues/7029
> Removed `depth infinity` related test and `dav.propfind.depth_infinity` from drone

- changelog/unreleased/bugfix-no-cache-pl
- src/publicLinkAccess.js
Just like we added the `noCache` option to `getFileContents`, I just realized the same needs to be applied to the public links after all.
Let me know if you prefer this as a parameter or something more generic.
> Optional no cache for public links

- tests/appsTest.js
- tests/capabilitiesTest.js
- tests/config/config.drone.json
- tests/config/config.sample.json
- tests/config/users.json
- tests/fileTrashTest.js
- tests/fileVersionTest.js
- tests/filesTest.js
- tests/groupTest.js
- tests/helpers/pactHelper.js
- tests/helpers/providerStateHelper.js
- tests/helpers/userHelper.js
- tests/loginTest.js
- tests/providerTest.js
- tests/publicLinkTest.js
- tests/requestsOcsTest.js
- tests/shareRecipientTest.js
- tests/sharingTest.js
- tests/sharingWithAttributesTest.js
- tests/signedUrlIntegrationTest.js
- tests/signedUrlTest.js
- tests/unauthorized/appsTest.js
- tests/unauthorized/capabilitiesTest.js
- tests/unauthorized/filesTest.js
- tests/unauthorized/groupTest.js
- tests/unauthorized/sharingTest.js
- tests/unauthorized/userTest.js
- tests/userTest.js
The main goal of this PR is to use the single structured config file for users so that the user config can be used both for tests and helper files.
This PR seems large but all the files have very similar changes.
Users are imported from new user config file.
part of https://github.com/owncloud/owncloud-sdk/issues/1086
> [tests-only] Refactor tests to use users from user config

- tests/fileVersionTest.js
- tests/helpers/httpHelper.js
- tests/helpers/pactHelper.js
- tests/helpers/sharingHelper.js
- tests/helpers/webdavHelper.js
- tests/providerTest.js
- tests/publicLinkTest.js
We have a `httpHelper` file. In this PR, I have refactored `sharingHelper` and `webdavHelper` files to use httpHelper for requests.
part of #1086
> Using httphelper in sharing and webdav helpers

- tests/fileTrashTest.js
- tests/fileVersionTest.js
- tests/filesTest.js
- tests/groupTest.js
- tests/helpers/pactHelper.js
- tests/helpers/providerStateHelper.js
- tests/helpers/webdavHelper.js
- tests/providerTest.js
- tests/publicLinkTest.js
- tests/shareRecipientTest.js
- tests/sharingWithAttributesTest.js
- tests/signedUrlIntegrationTest.js
- tests/userTest.js
For the Provider side tests, we have stateHandlers for pre-conditions. We have used state handlers directly in most of the tests but we also have state helper functions exactly for that.
State handler:
https://github.com/owncloud/owncloud-sdk/blob/4116766b9f90e6283d34bbb8eda2baae2ffaf02b/tests/providerTest.js#L112-L120
helper function:
https://github.com/owncloud/owncloud-sdk/blob/4116766b9f90e6283d34bbb8eda2baae2ffaf02b/tests/helpers/providerStateHelper.js#L25-L28
In this PR, I have refactored the tests to use state helper functions.
part of #1086
> Replace provider states with helper functions (p1)

- tests/fileTrashTest.js
- tests/fileVersionTest.js
- tests/filesTest.js
- tests/groupTest.js
- tests/helpers/pactHelper.js
- tests/helpers/providerStateHelper.js
- tests/helpers/webdavHelper.js
- tests/providerTest.js
- tests/publicLinkTest.js
- tests/requestsOcsTest.js
- tests/shareRecipientTest.js
- tests/sharingTest.js
- tests/sharingWithAttributesTest.js
- tests/signedUrlIntegrationTest.js
- tests/userTest.js
For the Provider side tests, we have stateHandlers for pre-conditions. We have used state handlers directly in most of the tests but we also have state helper functions exactly for that.
State handler:
https://github.com/owncloud/owncloud-sdk/blob/4116766b9f90e6283d34bbb8eda2baae2ffaf02b/tests/providerTest.js#L112-L120
helper function:
https://github.com/owncloud/owncloud-sdk/blob/4116766b9f90e6283d34bbb8eda2baae2ffaf02b/tests/helpers/providerStateHelper.js#L25-L28
In this PR, I have refactored the tests to use state helper functions.
part of #1086
> Replace provider states with helper functions (p2)

- tests/fileVersionTest.js
- tests/groupTest.js
- tests/helpers/providerStateHelper.js
- tests/helpers/sharingHelper.js
- tests/helpers/webdavHelper.js
- tests/providerTest.js
- tests/publicLinkTest.js
- tests/sharingTest.js
- tests/userTest.js
For the Provider side tests, we have stateHandlers for pre-conditions. We have used state handlers directly in most of the tests but we also have state helper functions exactly for that.
State handler:
https://github.com/owncloud/owncloud-sdk/blob/4116766b9f90e6283d34bbb8eda2baae2ffaf02b/tests/providerTest.js#L112-L120
helper function:
https://github.com/owncloud/owncloud-sdk/blob/4116766b9f90e6283d34bbb8eda2baae2ffaf02b/tests/helpers/providerStateHelper.js#L25-L28
In this PR, I have refactored the tests to use state helper functions.
part of #1086
> Replace provider states with helper functions (p3)

- changelog/unreleased/enhancement-token-info
- src/helperFunctions.js
- src/shareManagement.js
Works towards https://github.com/owncloud/web/issues/7304.
See https://github.com/cs3org/reva/pull/2687 for curl examples.
> Add methods for getting token infos

- .drone.star
- tests/drone/check-oCIS-cache.sh
**Description**
With this PR, the oCIS binary is cached inside the `cache_public_s3_bucket` as
```
s3/$CACHE_BUCKET/ocis-build/$OCIS_COMMITID
|__ ocis (binary)
``` 
The same setup is to be made on the owncloud/web CI, so that, if both repositories. uses the same commit id for oCIS, the binary can be shared.
**Related Issue:**
- Part of https://github.com/owncloud/QA/issues/756
- With https://github.com/owncloud/web/pull/7523
---
Signed-off-by: Kiran Parajuli <kiranparajuli589@gmail.com>
> [full-ci][tests-only] use oCIS from the global long term cache

- tests/config/config.sample.json
- tests/helpers/sharingHelper.js
- tests/sharingTest.js
Previously a constant expiration date was used and the nightly was failing since the expiration date is gone date than the current date. This PR adds a function to that gets the expiration date (+10 days with current date).
https://github.com/owncloud/owncloud-sdk/issues/1159
> [tests-only][full-ci]Added function to get expiration date instead of constant expiration date

- .drone.star
- tests/providerTest.js
The nightly failure was due to the failure in downloading the correct consumer pact file using the tag. We are currently using `DRONE_SOURCE_BRANCH` to create a tag for the pact version and also to download the correct pact version using this tag. But in cron builds, this env will be `undefined` thus causing the failure to download the latest expected pact version using `DRONE_SOURCE_BRANCH` as a tag.
In this PR, I have created a custom env `PACT_CONSUMER_VERSION_TAG` to store the tag name for the pact files. The tag name will be the branch name like before but with some conditions. For PRs, the tag name will be the PR branch name and for push/tags events the tag name will be the repo default branch name (`master`). 
Fixes https://github.com/owncloud/owncloud-sdk/issues/1159
> Use custom env  PACT_CONSUMER_VERSION_TAG for storing pact version tag

- .drone.env
Bumps oCIS commit ID for tests to the latest upto Oct 21, 2022.
https://github.com/owncloud/QA/issues/767
---
Signed-off-by: Kiran Parajuli <kiranparajuli589@gmail.com>
> [tests-only][full-ci] bump oCIS commit ID for the tests

- .drone.env
Bump latest `oCIS` commit-id to `owncloud-sdk`
https://github.com/owncloud/QA/issues/772
> [tests-only]Bump ocis latest commit-id on sdk

- .drone.star
Use the default workspace and only use the custom workspace for the oc10 pipeline.
The problem is caused due to the inconsistency in the paths. We build cache using `/drone/src` as a workspace and in some other pipelines, we use `/var/www/owncloud` as the workspace dir. This difference in paths was causing the caches to not be in the desired location.
Pipelines using `/var/www/owncloud` as workspace dir weren't getting the caches actually.
Explained by these images:
1. Pipelines using `/var/www/owncloud` dir
```bash
➤ YN0013: │ 3 packages were already cached, 1227 had to be fetched
```
2. Pipelines using `/drone/src` dir
```bash
➤ YN0013: │ 1229 packages were already cached
```
`dist` is available now: https://drone.owncloud.com/owncloud/owncloud-sdk/4007/4/4
Fixes …
> Use default workspace - make workspace consistent in all pipelines

- changelog/unreleased/bugfix-allow-removing-space-expiration-date
- src/shareManagement.js
`optionalParams.expireDate` is empty when it's being removed from a share. Hence we need to check for `undefined` explicitly.
Needed for https://github.com/owncloud/web/pull/8320.
> Allow removing expiration dates from space shares

- .gitignore
- changelog/unreleased/enhancement-share-space-with-group
- src/helperFunctions.js
- src/shareManagement.js
Adding a shareType `8` and a helper for inviting a group to a space.
> feat: add shareSpaceWithGroup

- src/fileManagement.js
- Enables passing of additional context for search and the used by it `_sendDavReport` function.
- In case of path set in the context, passes it to the REPORT request
Motivation:  
- CERNBox sdk search can only search inside the given repository, which needs to be passed to `_sendDavReport`
- Overall nice-to-have for ownCloud(?): the possibility to search inside the given repository in addition to all files
> Possibility to pass additional context for the search endpoint and _sendDavReport

- .drone.star
Currently CI is failing because of
```
+ cd /var/www/owncloud/server/
+ php occ config:system:set trusted_domains 1 --value=owncloud
This version of ownCloud requires at least PHP 7.4.0
You are currently running PHP 7.3.33-10+ubuntu18.04.1+deb.sury.org+1. Please update your PHP version.
```
So, this PR bumps the PHP version to 7.4, which is the required version
fixes: https://github.com/owncloud/owncloud-sdk/issues/1222
> [full-ci][tests-only]Bump PHP version to 7.4 for CI

- changelog/unreleased/enhancement-add-notifications
- src/shareManagement.js
Hi ownClouders :wave: 
This PR adds notification features to the SDK, to meet the changes in the [CS3APIs spec regarding notifications](https://cs3org.github.io/cs3apis/#cs3/sharing/link/v1beta1/link_api.proto), namely:
* The optional fields `notify_uploads` and `notify_uploads_extra_recipients`.
* A `notify` field to signal the backend to send a notification on a share creation.
It also includes a a `notifyShare` method to `shareManagement` that is used by web to send a notification reminder for a share.
These changes are already being used by the [CERNBox web](https://github.com/cernbox/web/commit/a2be88fa0510c36a63e419df2e08c72b37640992).
> Add notifications features

- README.md
See discussion in issue #924 - the version of pact is currently stuck, and we will investigate that again.
But for now, add this note so that developers will know this when they are following the instructions for running the tests locally.
> Document that node 14 is needed for the pact tests

- .drone.env
This PR bumps latest ocis commit id.
Part of https://github.com/owncloud/QA/issues/824
> [tests-only][full-ci] bumps ocis latest commit id

- .drone.env
- .drone.star
Part of: https://github.com/owncloud/QA/issues/826
> [tests-only] Bump commit id for tests

- changelog/unreleased/enhancement-add-ocs-error
- src/OCSError.js
- src/helperFunctions.js
Part of:
- https://github.com/owncloud/web/issues/9726
> Expose statusCode in OCSError

- package.json
- yarn.lock
mainly because of https://github.com/advisories/GHSA-wf5p-g6vw-rhxx
changelog see https://github.com/axios/axios/releases/tag/v0.28.0
> Bump axios from 0.27.2 to 0.28.0
